dbUrl = "jdbc:postgresql://localhost:15432/lmbot"
dbUser = "lmbot"
dbPassword = "lmbot"
httpHost = "127.0.0.1"
httpPort = 8080
cookieSecure = false
sessionTtl = "PT168H"
luxmedAppVersion = "4.44.0"
adminUsername = "admin"
adminPassword = "admin"
masterKey = "zipI+cHXewVqZsFi8jDDrAglsYK9B3fXZMswhyxr2hk="
liveLuxmedApi = false
embeddedPg = true
