dbUrl = "jdbc:postgresql://localhost:15432/lmbot"
dbUser = "lmbot"
dbPassword = "lmbot"
httpHost = "127.0.0.1"
httpPort = 8080
cookieSecure = false
sessionTtl = 7 days
luxmedAppVersion = "4.44.0"
adminUsername = "admin"
adminPassword = "admin"
masterKey = "zipI+cHXewVqZsFi8jDDrAglsYK9B3fXZMswhyxr2hk="
liveLuxmedApi = false
embeddedPg = true

dbUrl = ${?DATABASE_URL}
dbUser = ${?DATABASE_USER}
dbPassword = ${?DATABASE_PASSWORD}
adminUsername = ${?ADMIN_USERNAME}
adminPassword = ${?ADMIN_PASSWORD}
masterKey = ${?LMBOT_MASTER_KEY}
liveLuxmedApi = ${?LIVE_LUXMED_API}
embeddedPg = ${?EMBEDDED_PG}
