httpHost = "0.0.0.0"
httpPort = 8080
cookieSecure = true
sessionTtl = 7 days
liveLuxmedApi = false
embeddedPg = false
luxmedAppVersion = "4.44.0"

dbUrl = ${?DATABASE_URL}
dbUser = ${?DATABASE_USER}
dbPassword = ${?DATABASE_PASSWORD}
adminUsername = ${?ADMIN_USERNAME}
adminPassword = ${?ADMIN_PASSWORD}
masterKey = ${?LMBOT_MASTER_KEY}
liveLuxmedApi = ${?LIVE_LUXMED_API}
embeddedPg = ${?EMBEDDED_PG}
